-- CreateTable
CREATE TABLE "VALORACION" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(100),
    "CORREO" VARCHAR(100),
    "CALIFICACION" INTEGER NOT NULL,
    "COMENTARIO" TEXT,
    "FECHA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IP_CLIENTE" VARCHAR(45) NOT NULL,

    CONSTRAINT "VALORACION_pkey" PRIMARY KEY ("ID")
);
