-- CreateEnum
CREATE TYPE "estado_factura" AS ENUM ('EMITIDA', 'ANULADA');

-- CreateTable
CREATE TABLE "FACTURA" (
    "NRO" BIGSERIAL NOT NULL,
    "FECHA" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TOTAL" DECIMAL(12,2) NOT NULL,
    "ESTADO" "estado_factura" NOT NULL DEFAULT 'EMITIDA',
    "CLIENTE_CI" INTEGER NOT NULL,
    "PROFORMA_ID" BIGINT,

    CONSTRAINT "FACTURA_pkey" PRIMARY KEY ("NRO")
);

-- AddForeignKey
ALTER TABLE "FACTURA" ADD CONSTRAINT "FACTURA_CLIENTE_CI_fkey" FOREIGN KEY ("CLIENTE_CI") REFERENCES "CLIENTE"("CI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FACTURA" ADD CONSTRAINT "FACTURA_PROFORMA_ID_fkey" FOREIGN KEY ("PROFORMA_ID") REFERENCES "PROFORMA"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
